name: jurnee
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  http: ^1.5.0
  pinput: ^5.0.2
  google_maps_flutter: ^2.13.1
  widget_to_marker: ^1.0.6
  shimmer: ^3.0.0
  flutter_html: ^3.0.0
  flick_video_player: ^0.9.0
  video_player: ^2.10.0
  geolocator: ^14.0.1
  get: ^4.6.6
  intl: ^0.20.2
  socket_io_client: ^3.1.2
  geocoding: ^4.0.0
  file_picker: ^10.3.7
  uuid: ^4.5.2
  video_thumbnail: ^0.5.6
  path: ^1.9.1
  syncfusion_flutter_datepicker: ^31.1.19
  share_plus: ^12.0.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/language/
    - .env
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
